### ISSUE TITLE
Adding annoucement bar

### ISSUE THREAD

**Issue by irosenb** [ForeverFamilyFoundaton/forever-family-foundation#18]
Phran and I were talking about this. She wants a way to direct people to the conference page, so I proposed adding an annoucement bar at the top of the page. It'd look something like this: 

![image](https://cloud.githubusercontent.com/assets/1711479/4410238/71c512a2-44e4-11e4-8d56-eea9f32bbdba.png)

I suggested making it so that Phran could put up an announcement whenever she wants. She'd be able to add through the admin console. 

Looping @dinshaw in this.

**Comment by peterpih** [comment]
Annoucements PR #59 closes Issues #18
