### ISSUE TITLE
Sitterform Registration not showing up as checkbox in Admin

### ISSUE THREAD

**Issue by peterpih** [ForeverFamilyFoundaton/forever-family-foundation#197]
It's showing as a fill-in field, still works but "true" needs to be entered.

Shows as checkbox in test site and locally.

**Comment by railsnewbie257** [comment]
This seems to be due to the number of database connections maxing out (20/20)
The problem went away after 

> heroku reset --app forever-family-foundation

Solution is to upgrade database subscription from hobby-tier to standard-0-tier.

Closes #197
