### ISSUE TITLE
Preferences data is not accessible

### ISSUE THREAD

**Issue by ForeverFamilyFoundaton** [ForeverFamilyFoundaton/forever-family-foundation#7]
Upon new member sign up, they are asked to check off any of the following at the bottom of the registration page, but we do not get this information anyplace at our end.  Even in a CSV download, this information does not display.  Ideally, once someone asks for any of these things, we need to respond.  So we need some sort of notification system attached to it, or that shows on the Users list, or is included in te CSV download, which we do once a week to coordinate new members into  Constant Contact:
Send Me Signs Of Life Newsletter via email

Send Me Signs Of Life Newsletter via postal service (for residents of the US only)

I would like to be contacted about Volunteering my time to Forever Family Foundation

Please send me more information about Business Membership & Advertising Package

Please send me more information about becoming an Benefactor

Please contact me about making a Memorial Contribution

**Comment by peterpih** [comment]
This issue is closed
