### ISSUE TITLE
NoMethodError: undefined method `business' for nil:NilClass

### ISSUE THREAD

**Issue by peterpih** [ForeverFamilyFoundaton/forever-family-foundation#75]
From Honeybadger on Heroku(production):
Oldest · Previous · 11/05/15 @ 2:23 am +00:00 (4 days ago)
NoMethodError in businesses # new
This error has occurred 3 times since 11/04/15 @ 11:20 pm +00:00

This is caused by partially completing Business Registration and then resuming.
There seems to be some possible state confusion when Business::completed_step and session[] are out of sync.

**Comment by dinshaw** [comment]
Not fixing because we are redoing the whole registration.
